### PR TITLE
Fix VS Code Tasks on Linux

### PR DESCRIPTION
**Pull request by beverts312**
Address #66

### CODE REVIEW

**Comment by beverts312** [comment]
I still need to verify that this fix does not break windows

**Comment by calebcartwright** [comment]
not super related but.. i love this experience btw.. yo swell -> (wait for npm install to finish) -> code . -> Alert 'This workspace has recommended extensions' -> View recommended extensions

**Comment by calebcartwright** [comment]
this worked on windows just fine. I was expecting the commands to show in the integrated terminal at first, but see they come out just fine on output. 

looks like the 3 gulp tasks kicked off by the build button/script are clean, tslint, and transpile. Is this by design or should we consider having it emulate the npm build script? (include tests, etc.)

**Comment by beverts312** [comment]
Thats odd, the build button is tied to `npm run build` so it should run everything already

**Pull request merged**
