### PR TITLE
Updated VSTS-Task template files and scaffolding

### PR DESCRIPTION
**Pull request by calebcartwright**
Added additional functionality to the helper.ts file and started updating main.ts to make a call using async/await. Updated scaffolding process to seed the task.id with a real guid. Started adding docs to describe the generator/usage/etc.

### CODE REVIEW

**Comment by calebcartwright** [comment]
@beverts312 - I think I got the merge conflicts resolved correctly, but let me know if you have any objections. this is obviously still a work in progress, but I wanted to go ahead and address the merge conflicts before it got any more complicated

**Comment by beverts312** [comment]
lgtm

**Comment by calebcartwright** [comment]
@beverts312 excellent. it looks like codecov is hung again, going to look into what is wrong with travis-ci today..

**Comment by calebcartwright** [comment]
@beverts312 I think the issue may actually be a change that the codecov team made on their side. I am going to squash and merge via the override. both coveralls and codeclimate are reporting coverage is still at 100%

**Pull request merged**
