### PR TITLE
Bump requests typings to fix build

### PR DESCRIPTION
**Pull request by beverts312**
Bump requests typings to fix build

### CODE REVIEW

**Comment by beverts312** [comment]
looks like sonar is busted?

**Comment by calebcartwright** [comment]
oops, I commented on #91 instead of this one, but the request typings issue hit me the other day too

**Comment by beverts312** [comment]
@calebcartwright can you merge this one since it is passing circle?

**Comment by calebcartwright** [comment]
@beverts312 - sure. I've opened #93 to track fixing those integrations

**Comment by calebcartwright** [comment]
I didn't realize you were waiting on me for this. my bad :)

**Pull request merged**
